user_password: ENC[AES256_GCM,data:p0BK402UQsgFvYdhle9+blim3XtoIIqzMsFDJuRAQuLeHGS3LGjol2zoXt634bAD2Jr3qnVbkbeAudC6PiTilDn676cReEHJqIjMnD55NTtltHli4SQtDQ/ACG6vCkamaaCZS3HmLNCTDw==,iv:n+NYQRAkywCAWcgI5KtjagPpI00WiSRl7UqvJ/PPQLc=,tag:pAubraKgj9Da5LK3B8Tgsg==,type:str]
ssh_pub_key: ENC[AES256_GCM,data:695simCTI4CbLU8wAbPaKpBTUEuzaevF5rrc5wHjq3GvqHugSIe8Ng39208Tectam80HyoPBw5qnpRm2plx9sz70sv0AKf3trQ6mUJBva5yIcgj/ZFcJzMPkgqNRiP7YtfpYlxSq4/bqjK8UR3kw2K9x/YrjPa57Ehgu6w+d6Gh/HL3c,iv:LZ+BKwh0Wuxz+v5o4ovIF35ZZdWuJZWrKE/QM+uaXAk=,tag:LTJm4EFT5kPgCQulUsJ9wQ==,type:str]
ssh_password: ENC[AES256_GCM,data:4tpF1+ol8WSYKhlGxILq,iv:kRHC+r+z83ulynMlPPUdmnl/d6CZFnuDVXGmq0mdkig=,tag:Tmu7a1h/c/C78iq8IxfoqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wh035tyrjjtp7gqjgks80rzyttsdu7h5y4ktc0lstupp2pg905qs57ucfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbFpXaEZFb1BsNEZiSnI5
            S01iNG5ISktjS2JKU2VjYkhralk0V0tqdXlnCkxvemd6c1FzZGY1UTRzU0ZXVzMv
            bk4rakNQMEd2MUNnVDAyUmIyckVOYncKLS0tIGtjRWpSMTBQbmZwcm42VVJ3NFgw
            ako3Q3VKRk9wc1pPQ1U5cDUxdHdDdDgKy8TGkjOvz+LBUHJMgYK3acIWCJxExip0
            AZMXqMmvkVdJD4/PNXfH+GsGxcSZTKDyGYFV+qSb2hK8c1jx7uYPLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T00:48:23Z"
    mac: ENC[AES256_GCM,data:TndmHpR9Fy2KDIZXEgBTh2lorCfUy4R2qmZKnwdoqqC/b0vikU7VPA40OsW918uaQhNuHETYIksS8zD5OrImAsQSfA7PBurnKyG0SHP0+kkXv2U4Vd72MRu5nJ9Ya8KtL8zemofM7SI3l20a92PVwGRmrtH+dDa1Ak2DNxVoFEA=,iv:Xym/NiTuWzRiV/+/D+JW5vemk+9u05c030Z6ltztkYE=,tag:cvL4NCr8uDyvTNYmUeC/jQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
