user_password: ENC[AES256_GCM,data:6F6HpoSiKIkNqnku7681qR9l9ybGqdRn5H5/I5kIaAZG5xQCrKoaUK2uVkhU9fyl/K8N7Uf0/FzZ0t8uKxeWJ/FqLDmg4hiaaA==,iv:BhbgkD6Fux6WpRcovDNKR8SsercORMCSJKQMMnHGccQ=,tag:RWBRvMldMtrMU1avpmiugg==,type:str]
ssh_key_pub: ENC[AES256_GCM,data:IY1XANnR7MD6M1ReLCY0uKnyoIUkRwyYEc2kAP46jYGJPBDneS2Q52CK32LI7qUgfXbjjMkm/QcHyPiFYg/08t/ujM5MwupiNyhsDbJeOsRA19slynq44DDjpaT4zDu9zeNtpCuxtjpO426AKuLH9jvuAjUskbFMMHuVHs+BSDZU1XLh,iv:A2Fw2EZ74pEvCMpp4lSCBnwUPcd7GF23v4zQ85Hx/Eg=,tag:n9Fr2vO+je9f4Vl034yH7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wh035tyrjjtp7gqjgks80rzyttsdu7h5y4ktc0lstupp2pg905qs57ucfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbFpXaEZFb1BsNEZiSnI5
            S01iNG5ISktjS2JKU2VjYkhralk0V0tqdXlnCkxvemd6c1FzZGY1UTRzU0ZXVzMv
            bk4rakNQMEd2MUNnVDAyUmIyckVOYncKLS0tIGtjRWpSMTBQbmZwcm42VVJ3NFgw
            ako3Q3VKRk9wc1pPQ1U5cDUxdHdDdDgKy8TGkjOvz+LBUHJMgYK3acIWCJxExip0
            AZMXqMmvkVdJD4/PNXfH+GsGxcSZTKDyGYFV+qSb2hK8c1jx7uYPLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-19T14:56:34Z"
    mac: ENC[AES256_GCM,data:XS01ckMN0ebR9zYonGCc8faaUpLTLnSkJu1b9nyYIazFM1UthMc6uftGRDsilWhjoOhZjle3VGvWABRSd091PtDKbA8Z6O0bkxAcy1LT9isOdviA9PY6VNhupxVMKuKc6pDZ5eLpoJz3d4hArN3S27tYXTvW8Fq8Q+GCqCCYba0=,iv:yOBzV4INm0zT2REYXl9chsnoschvv9F4RmKpdKBD6Gc=,tag:v9So3rZpThc0ZbgCRU5nmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
