user_password: ENC[AES256_GCM,data:6F6HpoSiKIkNqnku7681qR9l9ybGqdRn5H5/I5kIaAZG5xQCrKoaUK2uVkhU9fyl/K8N7Uf0/FzZ0t8uKxeWJ/FqLDmg4hiaaA==,iv:BhbgkD6Fux6WpRcovDNKR8SsercORMCSJKQMMnHGccQ=,tag:RWBRvMldMtrMU1avpmiugg==,type:str]
ssh_key_pub: ENC[AES256_GCM,data:IY1XANnR7MD6M1ReLCY0uKnyoIUkRwyYEc2kAP46jYGJPBDneS2Q52CK32LI7qUgfXbjjMkm/QcHyPiFYg/08t/ujM5MwupiNyhsDbJeOsRA19slynq44DDjpaT4zDu9zeNtpCuxtjpO426AKuLH9jvuAjUskbFMMHuVHs+BSDZU1XLh,iv:A2Fw2EZ74pEvCMpp4lSCBnwUPcd7GF23v4zQ85Hx/Eg=,tag:n9Fr2vO+je9f4Vl034yH7A==,type:str]
cache_key_priv: ENC[AES256_GCM,data:6b7FWlXRRRUwqoqIu7Qds+dq8nGfFMbiH5gNpM7cemmhFDrqlUtteCagXi1hw1OmQphRBu4M2BJYHardH5Yw0sFKfo3NCgvEP+DTNTaNfPodsTihUWlzQ2sV0gk9Qzn2qg==,iv:syGlz52Eu5QSwmgWVDhj2F2iZb9qng64MB/ci7joZnA=,tag:OuMjjKYvMdVuU6kNxxiWeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wh035tyrjjtp7gqjgks80rzyttsdu7h5y4ktc0lstupp2pg905qs57ucfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbFpXaEZFb1BsNEZiSnI5
            S01iNG5ISktjS2JKU2VjYkhralk0V0tqdXlnCkxvemd6c1FzZGY1UTRzU0ZXVzMv
            bk4rakNQMEd2MUNnVDAyUmIyckVOYncKLS0tIGtjRWpSMTBQbmZwcm42VVJ3NFgw
            ako3Q3VKRk9wc1pPQ1U5cDUxdHdDdDgKy8TGkjOvz+LBUHJMgYK3acIWCJxExip0
            AZMXqMmvkVdJD4/PNXfH+GsGxcSZTKDyGYFV+qSb2hK8c1jx7uYPLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T19:35:45Z"
    mac: ENC[AES256_GCM,data:UCFa5WHmYU2SSxExe9L7zDc4AOxCYd2RU6HRvY7ADya3772o69J0wwa9ILhMBA9Zw+wHTy7rjXyQ/7JZk8Wm8jNdtwsdu0pDiBlnfy+9vl9lqwpkPL1r63auiFbSsq5yBobA0SP3A1c+3/QbErONFUF5WtC++LuOeQk3uQO2uig=,iv:0HfVC+Yt3qno0I/eXrUj7TUYdwP7NaHqRzFUItvD4ac=,tag:cOiUzmcgLUtM14eNYkKo8g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
