user_password: ENC[AES256_GCM,data:6F6HpoSiKIkNqnku7681qR9l9ybGqdRn5H5/I5kIaAZG5xQCrKoaUK2uVkhU9fyl/K8N7Uf0/FzZ0t8uKxeWJ/FqLDmg4hiaaA==,iv:BhbgkD6Fux6WpRcovDNKR8SsercORMCSJKQMMnHGccQ=,tag:RWBRvMldMtrMU1avpmiugg==,type:str]
cache_key_priv: ENC[AES256_GCM,data:ZDvr2G9N5KPql7AdFpi3wtrbuyzHQPSN6+1EwlMMXsn8I4XGvKJPHrl5SN1QCee+HUtjtAukOC8TbrV8Nm7BMvFWkLhCvr4rhmaT0PbX+3sJ0foFSccYqAf5reyrgQ==,iv:z7RX/Em4v9xrLiWJ1LvWzkTohBRfQJXjgQ9+rcNDvKc=,tag:kn+8YMT3YiDtZh+AGex/9Q==,type:str]
k3s_token: ENC[AES256_GCM,data:I8YWKpPWnir2lQenxUpoRwXNwbRElUuS/g==,iv:mfUnS7Uq8enPit29qHSMoM91oiULGaHBYfLsSjbpUBs=,tag:oBk3S6hu9XbWKPb6OOMgXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wh035tyrjjtp7gqjgks80rzyttsdu7h5y4ktc0lstupp2pg905qs57ucfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbFpXaEZFb1BsNEZiSnI5
            S01iNG5ISktjS2JKU2VjYkhralk0V0tqdXlnCkxvemd6c1FzZGY1UTRzU0ZXVzMv
            bk4rakNQMEd2MUNnVDAyUmIyckVOYncKLS0tIGtjRWpSMTBQbmZwcm42VVJ3NFgw
            ako3Q3VKRk9wc1pPQ1U5cDUxdHdDdDgKy8TGkjOvz+LBUHJMgYK3acIWCJxExip0
            AZMXqMmvkVdJD4/PNXfH+GsGxcSZTKDyGYFV+qSb2hK8c1jx7uYPLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T14:47:32Z"
    mac: ENC[AES256_GCM,data:pVHK7A50Svi2vO4GVnAgeppMd0zmuCkzYvn0FZj9u8c/ialtkiPR4nr0odmdPZykVS9f61SwQfijD98DnWzFX2Un0Eg1csCWtXt9s0BIb7YJWNJL0lPCY03P4FJl/mXhRgmRm0ZEexqfNYi/qU6tpg9slzAUJNn3YPCydhsLoXU=,iv:NM41XQKmM6Wmy5RDAfmo85OAQ4+KvXFIzeDppSgLPbc=,tag:Z9QHhmrgA0f5VBPSkwvQbw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
