user_password: ENC[AES256_GCM,data:KIdoFwpD01lOYxqxVzQcoaJ/IwliqQ+9t+Ej318lpePWceec1/ob6uZ/gjQCpMLA3NqHRg0bSVW39TqKunSTssb2XmHE2Wm1DapCl7joAlLE7dwiqUBDe9D52+LIODXv31PwMeKFhzMBOA==,iv:c+7Hs5C2+QUW5yg/LMzXqRVsUY6gHp6WUPtlWxvlWMs=,tag:G9UALM/ZN9OISvwU3qfCdQ==,type:str]
ssh_key_pub: ENC[AES256_GCM,data:DsdWYNdCqjdru96yT5PL3/iuHuQRntH9+NXxvhnNzTjs47XxRWQI8zt7n8HJGYT2orIGkIcWd4U876qYIO+Y8gDt8J+7ZBagu980CzgdsVayEuX9VNmkdt/YCBCvTvXDTZmkRt5Zw4hVOsE932HGSAdMXqTyayLPKOH7EpNc1iSi1nzG,iv:AxhfxgGGfHEYtuC/yT++TloPBQ4GLB3rQGMz6Z6go38=,tag:0VpeOfr/LV+Wjnr8YAHBIA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wh035tyrjjtp7gqjgks80rzyttsdu7h5y4ktc0lstupp2pg905qs57ucfc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbFpXaEZFb1BsNEZiSnI5
        S01iNG5ISktjS2JKU2VjYkhralk0V0tqdXlnCkxvemd6c1FzZGY1UTRzU0ZXVzMv
        bk4rakNQMEd2MUNnVDAyUmIyckVOYncKLS0tIGtjRWpSMTBQbmZwcm42VVJ3NFgw
        ako3Q3VKRk9wc1pPQ1U5cDUxdHdDdDgKy8TGkjOvz+LBUHJMgYK3acIWCJxExip0
        AZMXqMmvkVdJD4/PNXfH+GsGxcSZTKDyGYFV+qSb2hK8c1jx7uYPLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-01-16T04:10:07Z"
  mac: ENC[AES256_GCM,data:JjxeOMyuYZkHI0YK7l3TK3P69PCV0wwwzCeVTyOClj3ry9E0pU3k7moiNt/u6GgGEHP0MSEud9FBmOfFAHdJqC6IZ9eWa1pTKILYveaBxHaNTnAqWloTXfi3U6CepHmB028Sr8wchwZawHoFJDj3cXW5sXNIZ3ic2ddoy7tImJM=,iv:jgot/0ZIsknrlrDlremXImGmHyTzzZejubDcmqK0ZLQ=,tag:DGndPQ8Ge+cksO2vQ0aiwQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
